# Generated by Django 2.1.5 on 2019-11-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='', verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='post',
            name='fish_length',
            field=models.FloatField(verbose_name='Länge'),
        ),
        migrations.AlterField(
            model_name='post',
            name='fish_type',
            field=models.CharField(choices=[('Barsch', 'Barsch'), ('Hecht', 'Hecht'), ('Zander', 'Zander')], max_length=10, verbose_name='Fisch'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='post_pics/', verbose_name='Bild'),
        ),
    ]
