# Generated by Django 4.0 on 2022-02-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191108_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fish_type',
            field=models.CharField(choices=[('Barsch', 'Barsch'), ('Hecht', 'Hecht'), ('Zander', 'Zander'), ('Karpfen', 'Karpfen'), ('Schleie', 'Schleie'), ('Rotauge', 'Rotauge'), ('Wels', 'Wels'), ('Barbe', 'Barbe')], max_length=10, verbose_name='Fisch'),
        ),
    ]
